import re
from collections.abc import Generator, Mapping
from contextlib import contextmanager
from enum import StrEnum, auto
from typing import Any, Protocol

from lmstudio import Chat as LMStudioChat
from lmstudio import Client as LMStudioClient
from pydantic import Field
from pydantic.dataclasses import dataclass


class LLMProvider(StrEnum):
    LMSTUDIO = auto()


@dataclass
class ModelCaseResult:
    model_id: str = Field(title="Model ID", description="The identifier of the LLM model used for the test case.")
    case_name: str = Field(title="Test Case name", description="The name of the test case that was executed.")
    response: Mapping[str, Any] | str = Field(
        title="LLM Response", description="The response generated by the LLM for the given test case."
    )


@dataclass
class LLMTestCase:
    name: str = Field(title="Test Case name", description="The name of the test case.")
    raw_data: str = Field(title="Raw data", description="The raw input data for the test case.")
    json_schema: dict[str, Any] = Field(
        title="JSON Schema", description="The JSON schema that the LLM response should conform to."
    )


class LLMClientAdapter(Protocol):
    def __init__(self, api_host: str, system_prompt: str = "") -> None: ...
    def generate_response(
        self, client: Any, model_id: str, json_schema: dict[str, Any], raw_data
    ) -> Mapping[str, Any] | str: ...

    @contextmanager
    def get_client(self) -> Generator[Any]: ...

    def close(self) -> None: ...
    def run_test(self, model_ids: list[str], cases: list[LLMTestCase]) -> list[ModelCaseResult]: ...


class LMStudioClientAdapter:
    def __init__(self, api_host: str, system_prompt: str = "") -> None:
        self.__validate_api_host(api_host)
        self.api_host = api_host
        self.system_prompt = system_prompt
        self.client = LMStudioClient(api_host=self.api_host)

    def __validate_api_host(self, api_host: str) -> None:

        if not re.fullmatch(r"[a-zA-Z0-9\.\-]+:\d{1,5}", api_host):
            raise ValueError("api_host must match the format 'hostname:port', e.g., 'localhost:1234'.")
        _, port = api_host.split(":")
        if not (0 < int(port) < 65536):
            raise ValueError("Port number in api_host must be between 1 and 65535.")

    @contextmanager
    def get_client(self) -> Generator[LMStudioClient]:
        yield self.client

    def close(self) -> None:
        self.client.close()

    def generate_response(
        self, client: LMStudioClient, model_id: str, json_schema: dict[str, Any], raw_data: str
    ) -> Mapping[str, Any] | str:
        model = client.llm.model(model_id)
        try:
            chat = LMStudioChat(self.system_prompt)
            chat.add_user_message(raw_data)
            response = model.respond(chat, response_format=json_schema)
        finally:
            model.unload()
        return response.parsed

    def run_test(self, model_ids: list[str], cases: list[LLMTestCase]) -> list[ModelCaseResult]:
        results = []
        with self.get_client() as client:
            for model_id in model_ids:
                for case in cases:
                    response = self.generate_response(client, model_id, case.json_schema, case.raw_data)
                    results.append(ModelCaseResult(model_id=model_id, case_name=case.name, response=response))
        return results
