from typing import Any

import deepdiff
from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass(slots=True)
class Scores:
    similarity: float = Field(
        title="Similarity score",
        description="A score representing the percent similarity between the etalon and actual data.",
        ge=0.0,
        le=100.0,
    )
    field_match: float = Field(
        title="Field match score",
        description="A score representing the percent of fields that match between the etalon and actual data.",
        ge=0.0,
        le=100.0,
    )
    field_match_count: int = Field(
        title="Field match count",
        description="The count of fields that match between the etalon and actual data.",
        ge=0,
    )
    value_match: float = Field(
        title="Value match score",
        description="A score representing the percent of values that match between the etalon and actual data.",
        ge=0.0,
        le=100.0,
    )
    field_value_match_count: int = Field(
        title="Field value match count",
        description="The count of fields with matching values between the etalon and actual data.",
        ge=0,
    )


@dataclass(slots=True)
class EstimationRun:
    id: str = Field(title="Estimation run ID", description="Unique identifier for the estimation run.")
    etalon: dict[str, Any] = Field(
        title="Etalon data", description="The reference data against which the actual data will be compared."
    )
    actual: dict[str, Any] = Field(
        title="Actual data", description="The data generated by the LLM that needs to be evaluated."
    )


class Estimator:
    def __init__(self) -> None:
        self.scores: dict[str, Scores] = {}

    def estimate(self, run: EstimationRun) -> None:
        etalon_keys = set(run.etalon)
        actual_keys = set(run.actual)
        all_keys = etalon_keys | actual_keys
        common_keys = etalon_keys & actual_keys

        total_fields = len(all_keys)
        field_match_count = len(common_keys)
        field_match = 100.0 * field_match_count / total_fields if total_fields > 0 else 100.0

        field_value_match_count = sum(
            1 for key in common_keys if not deepdiff.DeepDiff(run.etalon[key], run.actual[key], ignore_order=True)
        )
        value_match = (
            100.0 * field_value_match_count / field_match_count
            if field_match_count > 0
            else (100.0 if total_fields == 0 else 0.0)
        )
        similarity = 100.0 * field_value_match_count / total_fields if total_fields > 0 else 100.0

        self.scores[run.id] = Scores(
            similarity=similarity,
            field_match=field_match,
            field_match_count=field_match_count,
            value_match=value_match,
            field_value_match_count=field_value_match_count,
        )

    def run(self, runs: list[EstimationRun]) -> dict[str, Scores]:
        self.scores = {}
        for run in runs:
            self.estimate(run)

        return self.scores
